 function ut(newimg)
newimg=imread('cropped_image.jpg');
p1=imresize(newimg,[400 NaN]);
figure,imshow(p1);
title('resized image');
p2=rgb2gray(p1);
figure,imshow(p2);
title('gray image');
level=graythresh(p2);
p2=imsharpen(p2);
figure,imshow(p2);
title('sharpened image');
p2=imadjust(p2);
figure,imshow(p2);
title('after imadjust');
p2=adapthisteq(p2);
figure,imshow(p2);
title('aftr histogramming');
p3=im2bw(p2);
figure,imshow(p3);
title('binary image');
p3=bwmorph(p3,'bridge',Inf);
figure,imshow(p3);
title('after bridging');
p3=medfilt2(p3,[3 3]);
figure,imshow(p3);
title('after median filtering');
se=strel('disk',4); 
gi=imdilate(p3,se);
figure,imshow(gi);
title('after dilating');
ge=imerode(p3,se);
figure,imshow(ge);
title('after erosion');
p4=imsubtract(gi,ge); 
figure,imshow(p4);
title('after subtaction');
p5=mat2gray(p4);
figure,imshow(p4);
title('from matrix to gray');
p5=conv2(p5,[1 1;1 1]);
figure,imshow(p5);
title('after convolution');
p5=imadjust(p5,[0.5 0.7],[0 1],0.1); 
figure,imshow(p5);
title('after adjustment');
B=logical(p5);
figure,imshow(B);
title('after logical op');
er=imopen(B,strel('line',level,0));
figure,imshow(er);
title('after open');
p6=imsubtract(B,er);
figure,imshow(p6);
title('after sub');
p6=bwmorph(p6,'bridge',Inf);
figure,imshow(p6);
title('after bridging');
p7=imfill(p6,'holes');
figure,imshow(p7);
title('afteer filling');
H=bwmorph(p7,'thin',1);
figure,imshow(H);
title('after thinning');
H=imerode(H,strel('line',4,0));
figure,imshow(H);
title('after erosion');
final=bwareaopen(H,250);
figure,imshow(final);
title('above 250 pixels');
final=~final;
imwrite(final,'c:\users\murali\documents\matlab\anpr\newocr.jpg');




